import unittest
from dataclasses import dataclass
from math import nan
from typing import Optional

from isolateparser.breseqparser.file_parsers.parse_vcf import *
# Need to also import private functions
from isolateparser.breseqparser.file_parsers.parse_vcf import _convert_record_to_dictionary, _convert_vcf_to_table, _filter_df

data_folder = Path(__file__).parent / 'data' / 'Clonal_Output' / 'breseq_output'
vcf_filename = data_folder / "data" / "output.vcf"

VCF_RECORDS = [{
	'seq id': 'REL606', 'position': 16971,
	'alt':    'GGGGTGGTTGTACTGACCCCAAAAAGTTGGACAGTTAAACACGAGGCATATAGGTCTGATTCCGATATTCAATTGGAGTCAGACCTTTTAATTTCAGGCTAATTCTTCTGCTGTTGTAGTATTCAATATATTCCGTAACAGCATCCTTCAGTTCGCTTATATTACTGAACTCATCAAGATAAAAACACTCCGACTTTAAGGTTCCAAAGAAACACTCCACCACAGCATTATCCAGACAATTGCCTTTTCTGGACATGCTTTGTTTAATACCATGTTCTTTAAGGATATTTTGATATCTTCTCATACGATACTGCCATCCCTGGTCAGAGTGCAGAACAGGATGCTCGTGAGGATTAAGCTTTTTGAATGCCTGATCGAGCATATTCTCAACCATGTTCATCACTGGTCTTTCCGAAAGGCTGTAAGAAATAACTTCGTTGTTGAAGAGATCTATTACTGGAGACAAATACAGCTTGCGCCCATTGACTGCAAATTCAGTAACATCGGTAACCCACTTCTCGTTTGGCCGCGTAGCCTTGAAATCTCTTTGGAGAACATTAGGGGCGGTTTGCCCTACCTCTCCTCTGTAAGAGCGGTATCGCTTGACCTTAATCGCTGCTTTAAGTGAGAGGGTTCCCATCAGGCGCTGAACAGCTTTATGGTTAATCTGTTTCCCTTCTCGATGAAGAGACAGCGTTACCCTACGGTATCCGTATCGGCCTCTATTCTCGTGATAAATCTCACTAATACGCTTTTTAACGTCCGCATACTTGTCAGGCTTGCTGAGAGCCTTTAGATGATAATAAAACGTACTGCGCGGTATCTCCGCAGCCCTGAGAAGCTCATCAAGAGGATAAAACTGCCTTAGCTCGTTGAGTACTTTCACTTTTTCGTGGGATGAGCTAAGGCTTTCAGCTTTTTTAGATACATAAGCCGCGTTTCAAGAAATCGAACTTGCCTTTCAAGATCCTCAATGCGTCGGTCTTTTGACAGCTCCAATGCTGATGCCGCTTTTTCTGGATCAACTGATATTGCAATGTTTCTTTTGGTGCCAATCTTGAGCGCGCGTAAACCAGCTTCTCCGCGCTCTTCATAGACCTTCAGCCACCTGGCTACAGAACCACTACCAGCAAGCATAAAGTGAGCAGCAGCCTGATTAAGGGACATGTGCTGCTCGATCACAGCTTTCACGACCTTAATACGCAACTCTGGATCAGCACTAACGCCTTTAGGTTTGGGAATTAAACCTTTTTCTCCATGTTTTTCATAGAGGGCAACCCATGTCCTGACCTGGGTTCGGGGGACACCAAAACGTGCCGAGATGATCCTGTAACCATCATCAGTTGTGAAGTAGTGATTCACGACTTCAAGGCGCTTTTCAAAAGGGTATTTTGGCTTTGACATATTAGGGGCTATTCCATTTCATCGTCCAACAAAATGGGTGCAGTACA',
	'ref':    'GG', 'quality': nan, 'readDepth': 59.5, 'variantType': 'indel'
}, {'seq id': 'REL606', 'position': 161041, 'alt': 'G', 'ref': 'T', 'quality': 190.1, 'readDepth': 61.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 380188, 'alt': 'C', 'ref': 'A', 'quality': 98.1, 'readDepth': 32.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 430835, 'alt': 'T', 'ref': 'C', 'quality': 135.0, 'readDepth': 48.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 475292, 'alt': 'GG', 'ref': 'G', 'quality': 94.7, 'readDepth': 32.0, 'variantType': 'indel'},
	{'seq id': 'REL606', 'position': 649391, 'alt': 'A', 'ref': 'T', 'quality': 161.3, 'readDepth': 54.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 668787, 'alt': 'C', 'ref': 'A', 'quality': 145.7, 'readDepth': 45.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 683496, 'alt': 'C', 'ref': 'A', 'quality': 192.0, 'readDepth': 60.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 910316, 'alt': 'C', 'ref': 'T', 'quality': 117.7, 'readDepth': 38.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 1004251, 'alt': 'C', 'ref': 'T', 'quality': 59.7, 'readDepth': 22.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 1248380, 'alt': 'C', 'ref': 'A', 'quality': 84.1, 'readDepth': 32.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 1286699, 'alt': 'A', 'ref': 'C', 'quality': 154.5, 'readDepth': 54.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 1329516, 'alt': 'T', 'ref': 'C', 'quality': 162.3, 'readDepth': 56.0, 'variantType': 'snp'}, {
		'seq id': 'REL606', 'position': 1733646,
		'alt':    'AAACAACATGTACTGACCCCAAAAAGTTGGACAGTTAAACACGAGGCATATAGGTCTGATTCCGATATTCAATTGGAGTCAGACCTTTTAATTTCAGGCTAATTCTTCTGCTGTTGTAGTATTCAATATATTCCGTAACAGCATCCTTCAGTTCGCTTATATTACTGAACTCATCAAGATAAAAACACTCCGACTTTAAGGTTCCAAAGAAACACTCCACCACAGCATTATCCAGACAATTGCCTTTTCTGGACATGCTTTGTTTAATACCATGTTCTTTAAGGATATTTTGATATCTTCTCATACGATACTGCCATCCCTGGTCAGAGTGCAGAACAGGATGCTCGTGAGGATTAAGCTTTTTGAATGCCTGATCGAGCATATTCTCAACCATGTTCATCACTGGTCTTTCCGAAAGGCTGTAAGAAATAACTTCGTTGTTGAAGAGATCTATTACTGGAGACAAATACAGCTTGCGCCCATTGACTGCAAATTCAGTAACATCGGTAACCCACTTCTCGTTTGGCCGCGTAGCCTTGAAATCTCTTTGGAGAACATTAGGGGCGGTTTGCCCTACCTCTCCTCTGTAAGAGCGGTATCGCTTGACCTTAATCGCTGCTTTAAGTGAGAGGGTTCCCATCAGGCGCTGAACAGCTTTATGGTTAATCTGTTTCCCTTCTCGATGAAGAGACAGCGTTACCCTACGGTATCCGTATCGGCCTCTATTCTCGTGATAAATCTCACTAATACGCTTTTTAACGTCCGCATACTTGTCAGGCTTGCTGAGAGCCTTTAGATGATAATAAAACGTACTGCGCGGTATCTCCGCAGCCCTGAGAAGCTCATCAAGAGGATAAAACTGCCTTAGCTCGTTGAGTACTTTCACTTTTTCGTGGGATGAGCTAAGGCTTTCAGCTTTTTTAGATACATAAGCCGCGTTTCAAGAAATCGAACTTGCCTTTCAAGATCCTCAATGCGTCGGTCTTTTGACAGCTCCAATGCTGATGCCGCTTTTTCTGGATCAACTGATATTGCAATGTTTCTTTTGGTGCCAATCTTGAGCGCGCGTAAACCAGCTTCTCCGCGCTCTTCATAGACCTTCAGCCACCTGGCTACAGAACCACTACCAGCAAGCATAAAGTGAGCAGCAGCCTGATTAAGGGACATGTGCTGCTCGATCACAGCTTTCACGACCTTAATACGCAACTCTGGATCAGCACTAACGCCTTTAGGTTTGGGAATTAAACCTTTTTCTCCATGTTTTTCATAGAGGGCAACCCATGTCCTGACCTGGGTTCGGGGGACACCAAAACGTGCCGAGATGATCCTGTAACCATCATCAGTTGTGAAGTAGTGATTCACGACTTCAAGGCGCTTTTCAAAAGGGTATTTTGGCTTTGACATATTAGGGGCTATTCCATTTCATCGTCCAACAAAATGGGTGCAGTACA',
		'ref':    'AA', 'quality': nan, 'readDepth': 62.0, 'variantType': 'indel'
	}, {
		'seq id': 'REL606', 'position': 1821524,
		'alt':    'ATTGGTGGTGTACTGACCCCAAAAAGTTGGACAGTTAAACACGAGGCATATAGGTCTGATTCCGATATTCAATTGGAGTCAGACCTTTTAATTTCAGGCTAATTCTTCTGCTGTTGTAGTATTCAATATATTCCGTAACAGCATCCTTCAGTTCGCTTATATTACTGAACTCATCAAGATAAAAACACTCCGACTTTAAGGTTCCAAAGAAACACTCCACCACAGCATTATCCAGACAATTGCCTTTTCTGGACATGCTTTGTTTAATACCATGTTCTTTAAGGATATTTTGATATCTTCTCATACGATACTGCCATCCCTGGTCAGAGTGCAGAACAGGATGCTCGTGAGGATTAAGCTTTTTGAATGCCTGATCGAGCATATTCTCAACCATGTTCATCACTGGTCTTTCCGAAAGGCTGTAAGAAATAACTTCGTTGTTGAAGAGATCTATTACTGGAGACAAATACAGCTTGCGCCCATTGACTGCAAATTCAGTAACATCGGTAACCCACTTCTCGTTTGGCCGCGTAGCCTTGAAATCTCTTTGGAGAACATTAGGGGCGGTTTGCCCTACCTCTCCTCTGTAAGAGCGGTATCGCTTGACCTTAATCGCTGCTTTAAGTGAGAGGGTTCCCATCAGGCGCTGAACAGCTTTATGGTTAATCTGTTTCCCTTCTCGATGAAGAGACAGCGTTACCCTACGGTATCCGTATCGGCCTCTATTCTCGTGATAAATCTCACTAATACGCTTTTTAACGTCCGCATACTTGTCAGGCTTGCTGAGAGCCTTTAGATGATAATAAAACGTACTGCGCGGTATCTCCGCAGCCCTGAGAAGCTCATCAAGAGGATAAAACTGCCTTAGCTCGTTGAGTACTTTCACTTTTTCGTGGGATGAGCTAAGGCTTTCAGCTTTTTTAGATACATAAGCCGCGTTTCAAGAAATCGAACTTGCCTTTCAAGATCCTCAATGCGTCGGTCTTTTGACAGCTCCAATGCTGATGCCGCTTTTTCTGGATCAACTGATATTGCAATGTTTCTTTTGGTGCCAATCTTGAGCGCGCGTAAACCAGCTTCTCCGCGCTCTTCATAGACCTTCAGCCACCTGGCTACAGAACCACTACCAGCAAGCATAAAGTGAGCAGCAGCCTGATTAAGGGACATGTGCTGCTCGATCACAGCTTTCACGACCTTAATACGCAACTCTGGATCAGCACTAACGCCTTTAGGTTTGGGAATTAAACCTTTTTCTCCATGTTTTTCATAGAGGGCAACCCATGTCCTGACCTGGGTTCGGGGGACACCAAAACGTGCCGAGATGATCCTGTAACCATCATCAGTTGTGAAGTAGTGATTCACGACTTCAAGGCGCTTTTCAAAAGGGTATTTTGGCTTTGACATATTAGGGGCTATTCCATTTCATCGTCCAACAAAATGGGTGCAGTACA',
		'ref':    'AT', 'quality': nan, 'readDepth': 62.5, 'variantType': 'indel'
	}, {'seq id': 'REL606', 'position': 1976879, 'alt': 'G', 'ref': 'T', 'quality': 159.8, 'readDepth': 47.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 2082685, 'alt': 'A', 'ref': 'G', 'quality': 90.6, 'readDepth': 31.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 2732014, 'alt': 'A', 'ref': 'C', 'quality': 116.0, 'readDepth': 38.0, 'variantType': 'snp'}, {
		'seq id': 'REL606', 'position': 3015770,
		'alt':    'ACCTTTCTTTTGTACTGACCCCAAAAAGTTGGACAGTTAAACACGAGGCATATAGGTCTGATTCCGATATTCAATTGGAGTCAGACCTTTTAATTTCAGGCTAATTCTTCTGCTGTTGTAGTATTCAATATATTCCGTAACAGCATCCTTCAGTTCGCTTATATTACTGAACTCATCAAGATAAAAACACTCCGACTTTAAGGTTCCAAAGAAACACTCCACCACAGCATTATCCAGACAATTGCCTTTTCTGGACATGCTTTGTTTAATACCATGTTCTTTAAGGATATTTTGATATCTTCTCATACGATACTGCCATCCCTGGTCAGAGTGCAGAACAGGATGCTCGTGAGGATTAAGCTTTTTGAATGCCTGATCGAGCATATTCTCAACCATGTTCATCACTGGTCTTTCCGAAAGGCTGTAAGAAATAACTTCGTTGTTGAAGAGATCTATTACTGGAGACAAATACAGCTTGCGCCCATTGACTGCAAATTCAGTAACATCGGTAACCCACTTCTCGTTTGGCCGCGTAGCCTTGAAATCTCTTTGGAGAACATTAGGGGCGGTTTGCCCTACCTCTCCTCTGTAAGAGCGGTATCGCTTGACCTTAATCGCTGCTTTAAGTGAGAGGGTTCCCATCAGGCGCTGAACAGCTTTATGGTTAATCTGTTTCCCTTCTCGATGAAGAGACAGCGTTACCCTACGGTATCCGTATCGGCCTCTATTCTCGTGATAAATCTCACTAATACGCTTTTTAACGTCCGCATACTTGTCAGGCTTGCTGAGAGCCTTTAGATGATAATAAAACGTACTGCGCGGTATCTCCGCAGCCCTGAGAAGCTCATCAAGAGGATAAAACTGCCTTAGCTCGTTGAGTACTTTCACTTTTTCGTGGGATGAGCTAAGGCTTTCAGCTTTTTTAGATACATAAGCCGCGTTTCAAGAAATCGAACTTGCCTTTCAAGATCCTCAATGCGTCGGTCTTTTGACAGCTCCAATGCTGATGCCGCTTTTTCTGGATCAACTGATATTGCAATGTTTCTTTTGGTGCCAATCTTGAGCGCGCGTAAACCAGCTTCTCCGCGCTCTTCATAGACCTTCAGCCACCTGGCTACAGAACCACTACCAGCAAGCATAAAGTGAGCAGCAGCCTGATTAAGGGACATGTGCTGCTCGATCACAGCTTTCACGACCTTAATACGCAACTCTGGATCAGCACTAACGCCTTTAGGTTTGGGAATTAAACCTTTTTCTCCATGTTTTTCATAGAGGGCAACCCATGTCCTGACCTGGGTTCGGGGGACACCAAAACGTGCCGAGATGATCCTGTAACCATCATCAGTTGTGAAGTAGTGATTCACGACTTCAAGGCGCTTTTCAAAAGGGTATTTTGGCTTTGACATATTAGGGGCTATTCCATTTCATCGTCCAACAAAATGGGTGCAGTACA',
		'ref':    'AC', 'quality': nan, 'readDepth': 53.5, 'variantType': 'indel'
	}, {'seq id': 'REL606', 'position': 3045069, 'alt': 'T', 'ref': 'G', 'quality': 78.7, 'readDepth': 27.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 3155168, 'alt': 'A', 'ref': 'G', 'quality': 133.4, 'readDepth': 43.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 3200643, 'alt': 'A', 'ref': 'C', 'quality': 156.1, 'readDepth': 51.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 3248957, 'alt': 'T', 'ref': 'A', 'quality': 174.5, 'readDepth': 60.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 3288092, 'alt': 'A', 'ref': 'G', 'quality': 143.7, 'readDepth': 44.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 3289961, 'alt': 'T', 'ref': 'TGTTGTACGATAAATCC', 'quality': nan, 'readDepth': 54.0, 'variantType': 'indel'},
	{'seq id': 'REL606', 'position': 3339158, 'alt': 'C', 'ref': 'A', 'quality': 157.7, 'readDepth': 49.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 3369432, 'alt': 'C', 'ref': 'T', 'quality': 202.5, 'readDepth': 63.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 3370027, 'alt': 'A', 'ref': 'T', 'quality': 178.6, 'readDepth': 56.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 3483047, 'alt': 'A', 'ref': 'C', 'quality': 150.4, 'readDepth': 48.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 3490112, 'alt': 'T', 'ref': 'C', 'quality': 169.6, 'readDepth': 57.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 3762741, 'alt': 'T', 'ref': 'A', 'quality': 103.0, 'readDepth': 37.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 3875632, 'alt': 'TT', 'ref': 'T', 'quality': 81.0, 'readDepth': 29.0, 'variantType': 'indel'},
	{'seq id': 'REL606', 'position': 3893551, 'alt': 'GG', 'ref': 'G', 'quality': 108.7, 'readDepth': 42.0, 'variantType': 'indel'}, {
		'seq id':  'REL606', 'position': 3894996, 'alt': 'A',
		'ref':     'AGACGCCTCCTTTCTTCATAAGGGGGCGTTTTTGTTTTCATGGTTAATCACCATGTAAAACGTTTCGAGGTTGATCACATTTCCGTAACGTCACGATGGTTTTCCCAACTCAGTCAGGATTAAACTGTGGGTCAGCGAAACGTTTCGCTGATGGAGAAAAAAATGAAAAAAGGCACCGTTCTTAATTCTGATATTTCATCGGTGATCTCCCGTCTGGGACATACCGATACGCTGGTGGTGTGTGATGCTGGTTTACCCATCCCCAAAAGTACAACGCGTATCGATATGGCATTAACCCAGGGTGTACCTTCTTTTATGCAGGTGCTGGGCGTCGTCACAAATGAAATGCAGGTCGAGGCTGCCATTATCGCGGAAGAGATCAAACAACATAATCCGCAACTCCACGAAACGTTGCTCACTCACCTTGAGCAGCTGCAAAAACACCAGGGAAATACCATTGAAATTCGTTACACCACGCATGAACAATTCAAACAACAAACCGCAGAAAGTCAGGCGGTAATTCGCAGCGGAGAATGTTCTCCGTATGCGAATATCATTCTCTGTGCTGGCGTGACGTTCTGAGGCCGTCATGGAAGCATTACTTCAGCTTAAAGGCATCGATAAAGCCTTCCCGGGCGTAAAAGCCCTCTCGGGCGCAGCGTTAAATGTCTATCCGGGCCGCGTGATGGCGCTGGTGGGCGAAAACGGCGCGGGTAAATCCACCATGATGAAAGTGCTTACTGGTATCTATGCTCGCGATGCCGGCACGCTTTTATGGCTGGGGAAAGAAACGACATTTACCGGGCCGAAATCTTCCCAGGAAGCCGGGATTGGGATTATCCATCAGGAACTGAACCTGATCCCGCAGTTGACCATTGCCGAAAACATTTTCCTCGGTCGTGAGTTTGTTAATCGCTTTGGCAAAATTGACTGGAAAACCATGTATGCCGAAGCGGATAAATTGCTGGCTAAACTTAACCTGCGCTTTAAAAGCGACAAGCTGGTGGGCGATCTTTCCATCGGTGACCAGCAAATGGTTGAAATCGCCAAAGTGCTGAGCTTTGAGTCGAAAGTCATCATTATGGATGAACCGACCGATGCGCTGACCGATACCGAAACCGAATCCCTGTTCCGCGTCATCCGCGAGCTGAAATCGCAAGGCCGCGGTATTGTCTATATCTCCCACCGCATGAAAGAAATCTTCGAGATTTGCGATGACGTTACCGTTTTTCGTGATGGGCAATTTATTGCTGAGCGCGAAGTGGCATCACTGACCGAAGATTCGCTGATTGAGATGATGGTGGGTCGCAAGCTGGAAGATCAATATCCGCACCTGGACAAAGCGCCGGGAGATATCCGCCTGAAAGTCGATAATCTCTGCGGACCTGGCGTTAACGATGTCTCTTTTACTTTACGCAAAGGCGAAATTCTTGGCGTCTCTGGTTTGATGGGCGCAGGTCGTACCGAACTGATGAAAGTGCTCTACGGCGCACTACCGCGCACCAGCGGTTACGTCACCCTGGATGGGCATGAAGTCGTTACCCGTTCACCGCAGGATGGCCTGGCAAACGGCATTGTGTATATCTCCGAAGACCGTAAACGTGACGGTTTAGTGTTGGGCATGTCAGTAAAAGAGAACATGTCGCTGACAGCGCTGCGCTACTTCAGCCGCGCTGGCGGCAGTTTGAAGCATGCCGATGAACAGCAGGCTGTGAGTGATTTCATTCGTCTGTTTAATGTGAAAACTCCGTCGATGGAACAGGCAATTGGTCTGCTTTCCGGTGGCAATCAGCAAAAAGTGGCGATTGCCCGCGGTCTGATGACACGCCCCAAAGTGTTGATCCTTGATGAACCTACCCGTGGCGTAGATGTCGGCGCGAAAAAAGAGATCTATCAACTGATTAACCAGTTCAAAGCCGATGGCTTGAGCATCATTCTGGTGTCATCGGAGATGCCAGAAGTATTAGGCATGAGCGATCGCATCATCGTCATGCATGAAGGGCATCTCAGCGGGGAATTTACTCGTGAGCAGGCCACCCAGGAAGTGTTAATGGCTGCCGCTGTGGGCAAGCTTAATCGCGTGAATCAGGAGTAAAAAAATGACAACCCAGACTGTCTCTGGTCGCCGTTATTTCACGAAAGCGTGGCTGATGGAGCAGAAATCGCTTATCGCTCTGCTGGTGCTGATCGCGATTGTCTCGACGTTAAGCCCGAACTTTTTCACCATCAATAACTTATTCAATATTCTCCAGCAAACCTCAGTGAACGCCATTATGGCGGTCGGGATGACGCTGGTGATCCTGACGTCGGGCATCGACTTATCGGTAGGTTCTCTGTTGGCGCTGACCGGCGCAGTTGCTGCATCTATCGTCGGCATTGAAGTCAATGCGCTGGTGGCTGTCGCTGCTGCTCTCGCGTTAGGTGCCGCAATTGGTGCGGTAACCGGGGTGATTGTAGCGAAAGGTCGCGTCCAGGCGTTTATCGCTACGCTGGTTATGATGCTTTTACTGCGCGGCGTGACCATGGTTTATACCAACGGTAGCCCAGTGAATACCGGCTTTACTGAGAACGCCGATCTGTTTGGCTGGTTTGGTATTGGTCGTCCGCTGGGCGTACCGACGCCAGTCTGGATCATGGGGATTGTCTTCCTCGCGGCCTGGTACATGCTGCATCACACGCGTCTGGGGCGTTACATCTACGCGCTGGGCGGCAACGAAGCGGCAACGCGTCTTTCTGGTATCAACGTCAATAAAATCAAAATCATCGTCTATTCTCTTTGTGGTCTGCTGGCATCGCTGGCCGGGATCATTGAAGTGGCGCGTCTCTCCTCCGCACAACCCACGGCGGGGACTGGCTATGAGCTGGATGCTATTGCTGCGGTGGTTCTGGGCGGTACGAGTCTGGCGGGCGGAAAAGGTCGCATTGTTGGGACGTTGATCGGCGCATTAATTCTTGGCTTCCTTAATAATGGATTGAATTTGTTAGGTGTTTCCTCCTATTACCAGATGATCGTCAAAGCGGTGGTGATTTTGCTGGCGGTGCTGGTAGACAACAAAAAGCAGTAATAACGACTACAGGACATCTTGAATATGAACATGAAAAAACTGGCTACCCTGGTTTCCGCTGTTGCGCTAAGCGCCACCGTCAGTGCGAATGCGATGGCAAAAGACACCATCGCGCTGGTGGTCTCCACGCTTAACAACCCGTTCTTTGTATCGCTGAAAGATGGCGCGCAGAAAGAGGCGGATAAACTTGGCTATAACCTGGTGGTGCTGGACTCCCAGAACAACCCGGCGAAAGAGCTGGCGAACGTGCAGGACTTAACCGTTCGCGGCACAAAAATTCTGCTGATTAACCCGACCGACTCCGACGCAGTGGGTAATGCTGTGAAGATGGCTAACCAGGCGAACATCCCGGTTATCACTCTTGACCGCCAGGCAACGAAAGGTGAAGTGGTGAGCCACATTGCTTCTGATAACGTACTGGGTGGCAAAATCGCCGGTGATTACATCGCGAAGAAAGCGGGTGAAGGTGCCAAAGTTATCGAGCTGCAAGGCATTGCTGGTACATCCGCAGCCCGTGAACGTGGCGAAGGCTTCCAGCAGGCCGTTGCTGCTCACAAGTTTAATGTTCTTGCCAGCCAGCCAGCAGATTTTGATCGCACCAAAGGTTTGAACGTAATGCAGAACCTGTTGACCGCTCATCCGGATGTTCAGGCTGTATTTGCGCAGAATGATGAAATGGCGCTGGGCGCGCTGCGCGCACTGCAAACTGCCGGTAAATCGGATGTGATGGTCGTCGGATTTGACGGTACACCGGATGGCGAAAAAGCGGTGAATGATGGCAAACTAGCAGCGACTATCGCTCAGCTACCCGATCAGATTGGCGCGAAAGGCGTCGAAACCGCAGATAAAGTGCTGAAAGGCGAGAAAGTTCAGGCTAAGTATCCGGTTGATCTGAAACTGGTTGTTAAGCAGTAGTTTTAATCAGGTTGTATGACCTGATGGTGACATAAATACGTCATCGACAGATGAACGTGTAATATAAAGAAAAGCAGGGCACGCGCCACCCTAACACGGTGGCGCATTTTATGGACATCCCGAATATGCAAAACGCAGGCAGCCTCGTTGTTCTTGGCAGCATTAATGCTGACCACATTCTTAATCTTCAATCTTTTCCTTCCCCAGGCGAAACCGTAACCGGTAACCACTATCAGGTTGCATTTGGCGGCAAAGGCGCGAATCAGGCGGTGGCTGCTGGGCGTAGCGGTGCGAATATCGCGTTTATTGCCTGCACTGGCGATGACAGCATTGGCGAGAGCGTTCGCCAGCAGCTCGCCACTGATAACATCGATATTTCTCCCGTCAGCGTGATCAAAGGCGAATCAACAGGTGTGGCGCTGATTTTTGTTAATGGCGAAGGTGAGAATGTCATTGGTATTCATGCCGGCGCTAATGCTGCCCTTTCCCCGGCGCTGGTGGAAGCGCAACGTGAGCGTATTGCCAACGCATCAGCATTATTAATGCAGCTGGAATCACCACTCGAAAGTGTGATGGCAGCGGCGAAAATCGCCCATCAAAATAAGACTATCGTTGCGCTTAACCCGGCTCCGGCTCGCGAACTTCCTGACGAACTGCTGGCGCTGGTGGACATTATTACGCCAAACGAAACGGAAGCAGAAAAGCTCACCGGTATTCGTGTTGAAAATGATGAAGATGCAGCGAAGGCGGCGCAGGTACTGCATGAAAAAGGTATCCGTACTGTACTGATTACTTTAGGAAGTCGTGGTGTATGGGCTAGCGTGAATGGTGAAGGTCAGCGCGTTCCTGGATTCCGGGTGCAGGCTGTCGATACCATTGCTGCCGGAGATACCTTTAACGGTGCGTTAATCACGGCATTGCTGGAAGAAAAACCATTGCCAGAGGCGATTCGTTTTGCCCATGCTGCCGCTGCGATTGCCGTAACACGTAAAGGCGCACAACCTTCCGTACCGTGGCGTGAAGAGATCGACGCATTTTTAGACAGGCAGAGGTGACGCTTGGCTACAATGAAAGATGTTGCCCGCCTGGCGGGCGTTTCTACCTCAACAGTTTCTCACGTTATCAATAAAGATCGCTTCGTCAGTGAAGCGATTACCGCCAAAGTTGAAGCGGCGATTAAAGAACTCAATTACGCGCCATCAGCTCTGGCGCGTAGCCTCAAACTCAATCAAACACATACCATTGGCATGTTGATCACTGCCAGTACCAATCCTTTCTATTCAGAACTGGTGCGTGGCGTTGAACGCAGCTGCTTCGAACGCGGTGATAGTCTTGTCCTTTGCAATACCGAAGGCGATGAACAGCGGATGAATCGCAATCTGGAAACGCTGATGCAAAAACGCGTTGATGGCTTGCTGTTACTGTGCACCGAAACGCATCAGCCTTCGCGTGAAATCATGCAACGTTATCCGACAGTGCCTACCGTGATGATGGACTGGGCTCCGTTCGATGGCGACAGCGATCTTATTCAGGATAACTCGTTGCTGGGCGGAGACTTAGCAACGCAATATCTGATCGATAAAGGTCATACCCGTATCGCCTGTATTACCGGCCCGCTGGATAAAACTCCGGCGCGCCTGCGGTTGGAAGGTTATCGGGCGGCGATGAAACGTGCGGGTCTCAACATTCCTGATGGCTATGAAGTCACTGGTGATTTTGAATTTAACGGCGGGTTTGACGCTATGCGCCAACTGCTATCACATCCGCTGCGTCCTCAGGCCGTCTTTACCGGAAATGACGCTATGGCTGTTGGCGTTTACCAGGCGTTATATCAGGCAGAGTTACAGGTTCCGCAGGATATCGCGGTGATTGGCTATGACGATATCGAACTGGCAAGCTTTATGACGCCACCATTAACCACTATCCACCAACCGAAAGATGAACTGGGGGAGCTGGCGATTGATGTACTCATCCATCGGATAACCCAGCCAACTCTTCAGCAACAACGATTACAACTTACTCCGATTCTGATGGAACGCGGTTCGGCTTAGATTTACGCTGTCTTTTGATCAAATTATTACCATCGGTTGTTTTCAGAAGCATGAACATTGCTGCTGAAGCAACAGTAATAATGCCCATTGTGATAAACGTATAGTGGAATTGTTCGACAGTCGTTGTGCCTTCCATTCCTTCATAAACGCGAAGGACGGCCGCACTTACAGCAACGCCTAAACTGATAGACAGTTGCTGCGTGACCGCCAGAACACTGTTACCGCTGCTGGCGTTGTCATCGGTCAGATCGGCAAGTGTGATGGTATTCATCGCGGTAAACTGCGTCGACATAGCCATCCCTAATATAAACAACGGCAAGATCAGCATCCATATCGCCATTGCCGGTGATTGCAAAGAGAACTGAGCGATCATTAGCCCAATAATCACCGTGATCCCCACTAATGTATGGCGATAGCCCAGACGACGTAAGACTTGGGTAACCATCGATTTTGCAATAATGGAACCTAACGCTGTCGGCGCCATCATACAGCCGGCAATAAACGCCTGATAACCAAATCCTACCTGTAACATCAATGGCATAAGGAACGGTACACAGCCGGTCCCCAGACGGGTTGCAATATTGCCTACGATACCGATCGAGAAAGTGCGGGTTTTAAATAAATCTAATGAAATTAATGGGTTTGGCGTGCGTCGTGCATGGAGAATATAGAGAAGCAGTAACCCGATGCTGGTGACAATTACCGTCAAGGCAATCCAGCTGGCGACAATCTTTTCCCCGAATAGCTCTATTCCGCTTGAGAAGAGAACAAGGCTGAGGCCAAACAACAAAAAGCCAGTGATATCGAATCTGCGTCGTGCGGTGGTGAAATTGGGCATATGTTTGCGCGCGTAAAGAAGGCCTGCAATACCTATGGGGATATTGATTAAAAATATCCAGTGCCA',
		'quality': nan, 'readDepth': 35.0, 'variantType': 'indel'
	}, {'seq id': 'REL606', 'position': 4100655, 'alt': 'T', 'ref': 'C', 'quality': 117.3, 'readDepth': 39.0, 'variantType': 'snp'},
	{'seq id': 'REL606', 'position': 4126705, 'alt': 'T', 'ref': 'TT', 'quality': 57.2, 'readDepth': 16.0, 'variantType': 'indel'},
	{'seq id': 'REL606', 'position': 4201911, 'alt': 'T', 'ref': 'C', 'quality': 174.3, 'readDepth': 59.0, 'variantType': 'snp'}, {
		'seq id': 'REL606', 'position': 4524521,
		'alt':    'GCCCGCAACCGCAACCCATAAGCGCTAACTTAAGGGTTGTGGTATTACGCCTGATATGATTTAACGTGCCGATGAATTACTCTCACGATAACTGGTCAGCAATTCTGGCCCATATTGGTAAGCCCGAAGAACTGGATACTTCGGCACGTAATGCCGGGGCTCTAACCCGCCGCCGCGAAATTCGTGATGCTGCAACTCTGCTACGTCTGGGGCTGGCTTACGGCCCCGGGGGGATGTCATTACGTGAAGTCACTGCATGGGCTCAGCTCCATGACGTTGCAACATTATCTGACGTGGCTCTCCTGAAGCGGCTGCGGAATGCCGCCGACTGGTTTGGCATACTTGCCGCACAAACACTTGCTGTACGCGCCGCAGTTACGGGTTGTACAAGCGGAAAGAGATTGCGTCTTGTCGATGGAACAGCAATCAGTGCGCCCGGGGGCGGCAGCGCTGAATGGCGACTACATATGGGATATGATCCTCATACCTGTCAGTTCACTGATTTTGAGCTAACCGACAGCAGAGACGCTGAACGGCTGGACCGATTTGCGCAAACGGCAGACGAGATACGCATTGCTGACCGGGGATTCGGTTCGCGTCCCGAATGTATCCGCTCACTTGCTTTTGGAGAAGCTGATTATATCGTCCGGGTTCACTGGCGAGGATTGCGCTGGTTAACTGCAGAAGGAATGCGCTTTGACATGATGGGTTTTCTGCGCGGGCTGGATTGCGGTAAGAACGGTGAAACCACTGTAATGATAGGCAATTCAGGTAATAAAAAAGCCGGAGCTCCCTTTCCGGCACGTCTCATTGCCGTATCACTTCCTCCCGAAAAAGCATTAATCAGTAAAACCCGACTGCTCAGCGAGAATCGTCGAAAAGGACGAGTAGTTCAGGCGGAAACGCTGGAAGCAGCGGGCCATGTGCTATTGCTAACATCATTACCGGAAGATGAATATTCAGCAGAGCAAGTGGCTGATTGTTACCGTCTGCGATGGCAAATTGAACTGGCTTTTAAGCGGCTCAAAAGTTTGCTGCACCTGGATGCTTTGCGTGCAAAGGAACCTGAACTCGCGAAAGCGTGGATATTTGCTAATCTACTCGCCGCATTTTTAATTGACGACATAATCCAGCCATCGCTGGATTTCCCCCCCAGAAGTGCCGGATCCGAAAAGAAGAACTAACTCGTTGTGGAGAATAACAAAAATGGTCATCTGGAGCTTACAGGTGGCCATTCGTGGGACAGTATCCCTGACAGCCTACAAAACGCAATTGAAGAACGCGAGGCATCGTCTTAACGAGGCACCGAGGCGTCGCATTCTTCAGATGGTTCAACCCTTAAGTTAGCGCTTATGGG',
		'ref':    'GC', 'quality': nan, 'readDepth': 52.5, 'variantType': 'indel'
	}, {'seq id': 'REL606', 'position': 4616396, 'alt': 'A', 'ref': 'G', 'quality': 164.6, 'readDepth': 55.0, 'variantType': 'snp'}]
SNP_RECORDS = [i for i in VCF_RECORDS if i['variantType'] == 'snp']


@dataclass
class Record:
	""" Easier to emulate a VCF Record rather than instantiate vcf._Record"""
	ALT: List[str]
	REF: str
	QUAL: Optional[float]
	INFO: Dict[str, Any]
	CHROM: str
	POS: int
	var_type: str


class TestVCFParser(unittest.TestCase):
	def test_get_vcf_filename(self):
		self.assertEqual(vcf_filename, get_vcf_filename(vcf_filename))
		self.assertEqual(vcf_filename, get_vcf_filename(vcf_filename.parent))
		with self.assertRaises(FileNotFoundError):
			get_vcf_filename(Path())

	def test_convert_record_to_dictionary(self):
		record = Record(
			CHROM = 'REL606',
			POS = 16971,
			REF = "GG",
			ALT = [
				"GGGGTGGTTGTACTGACCCCAAAAAGTTGGACAGTTAAACACGAGGCATATAGGTCTGATTCCGATATTCA"
				"ATTGGAGTCAGACCTTTTAATTTCAGGCTAATTCTTCTGCTGTTGTAGTATTCAATATATTCCGTAACAGC"
				"ATCCTTCAGTTCGCTTATATTACTGAACTCATCAAGATAAAAACACTCCGACTTTAAGGTTCCAAAGAAAC"
				"ACTCCACCACAGCATTATCCAGACAATTGCCTTTTCTGGACATGCTTTGTTTAATACCATGTTCTTTAAGG"
				"ATATTTTGATATCTTCTCATACGATACTGCCATCCCTGGTCAGAGTGCAGAACAGGATGCTCGTGAGGATT"
				"AAGCTTTTTGAATGCCTGATCGAGCATATTCTCAACCATGTTCATCACTGGTCTTTCCGAAAGGCTGTAAG"
				"AAATAACTTCGTTGTTGAAGAGATCTATTACTGGAGACAAATACAGCTTGCGCCCATTGACTGCAAATTCA"
				"GTAACATCGGTAACCCACTTCTCGTTTGGCCGCGTAGCCTTGAAATCTCTTTGGAGAACATTAGGGGCGGT"
				"TTGCCCTACCTCTCCTCTGTAAGAGCGGTATCGCTTGACCTTAATCGCTGCTTTAAGTGAGAGGGTTCCCA"
				"TCAGGCGCTGAACAGCTTTATGGTTAATCTGTTTCCCTTCTCGATGAAGAGACAGCGTTACCCTACGGTAT"
				"CCGTATCGGCCTCTATTCTCGTGATAAATCTCACTAATACGCTTTTTAACGTCCGCATACTTGTCAGGCTT"
				"GCTGAGAGCCTTTAGATGATAATAAAACGTACTGCGCGGTATCTCCGCAGCCCTGAGAAGCTCATCAAGAG"
				"GATAAAACTGCCTTAGCTCGTTGAGTACTTTCACTTTTTCGTGGGATGAGCTAAGGCTTTCAGCTTTTTTA"
				"GATACATAAGCCGCGTTTCAAGAAATCGAACTTGCCTTTCAAGATCCTCAATGCGTCGGTCTTTTGACAGC"
				"TCCAATGCTGATGCCGCTTTTTCTGGATCAACTGATATTGCAATGTTTCTTTTGGTGCCAATCTTGAGCGC"
				"GCGTAAACCAGCTTCTCCGCGCTCTTCATAGACCTTCAGCCACCTGGCTACAGAACCACTACCAGCAAGCA"
				"TAAAGTGAGCAGCAGCCTGATTAAGGGACATGTGCTGCTCGATCACAGCTTTCACGACCTTAATACGCAAC"
				"TCTGGATCAGCACTAACGCCTTTAGGTTTGGGAATTAAACCTTTTTCTCCATGTTTTTCATAGAGGGCAAC"
				"CCATGTCCTGACCTGGGTTCGGGGGACACCAAAACGTGCCGAGATGATCCTGTAACCATCATCAGTTGTGA"
				"AGTAGTGATTCACGACTTCAAGGCGCTTTTCAAAAGGGTATTTTGGCTTTGACATATTAGGGGCTATTCCA"
				"TTTCATCGTCCAACAAAATGGGTGCAGTACA"
			],
			var_type = 'indel',
			INFO = {'AF': [1.0], 'AD': 59.5, 'DP': 59.5},
			QUAL = None
		)
		data = {
			VCFColumns.sequence_id:  'REL606',
			VCFColumns.position:     16971,
			VCFColumns.alternate:    record.ALT[0],
			VCFColumns.reference:    "GG",
			VCFColumns.quality:      None,
			VCFColumns.depth:        59.5,
			VCFColumns.variant_type: 'indel'
		}
		output = _convert_record_to_dictionary(record)

		self.assertDictEqual(data, output)

	def test_parse_vcf_file(self):
		columns = ['seq id', 'position', 'alt', 'ref', 'quality', 'readDepth', 'variantType']

		vcf_table = parse_vcf_file(vcf_filename, set_index = False, no_filter = True)

		self.assertListEqual(columns, list(vcf_table.columns))
		snp_table = vcf_table[vcf_table['variantType'] == 'snp']
		self.assertListEqual(SNP_RECORDS, snp_table.to_dict(orient = 'records'))

		vcf_table = parse_vcf_file(vcf_filename, set_index = True, no_filter = True)
		truth_index = """REL606	16971
			REL606	161041
			REL606	380188
			REL606	430835
			REL606	475292
			REL606	649391
			REL606	668787
			REL606	683496
			REL606	910316
			REL606	1004251
			REL606	1248380
			REL606	1286699
			REL606	1329516
			REL606	1733646
			REL606	1821524
			REL606	1976879
			REL606	2082685
			REL606	2732014
			REL606	3015770
			REL606	3045069
			REL606	3155168
			REL606	3200643
			REL606	3248957
			REL606	3288092
			REL606	3289961
			REL606	3339158
			REL606	3369432
			REL606	3370027
			REL606	3483047
			REL606	3490112
			REL606	3762741
			REL606	3875632
			REL606	3893551
			REL606	3894996
			REL606	4100655
			REL606	4126705
			REL606	4201911
			REL606	4524521
			REL606	4616396""".split("\n")
		truth_index = [i.strip().split("\t") for i in truth_index]
		truth_index = [(i[0], int(i[1])) for i in truth_index]
		self.assertListEqual(truth_index, list(vcf_table.index))

	def test_convert_vcf_to_table(self):
		record = Record(
			CHROM = 'REL606',
			POS = 16971,
			REF = "GG",
			ALT = [
				"GGGGTGGTTGTACTGACCCCAAAAAGTTGGACAGTTAAACACGAGGCATATAGGTCTGATTCCGATATTCA"
				"ATTGGAGTCAGACCTTTTAATTTCAGGCTAATTCTTCTGCTGTTGTAGTATTCAATATATTCCGTAACAGC"
				"ATCCTTCAGTTCGCTTATATTACTGAACTCATCAAGATAAAAACACTCCGACTTTAAGGTTCCAAAGAAAC"
				"ACTCCACCACAGCATTATCCAGACAATTGCCTTTTCTGGACATGCTTTGTTTAATACCATGTTCTTTAAGG"
				"ATATTTTGATATCTTCTCATACGATACTGCCATCCCTGGTCAGAGTGCAGAACAGGATGCTCGTGAGGATT"
				"AAGCTTTTTGAATGCCTGATCGAGCATATTCTCAACCATGTTCATCACTGGTCTTTCCGAAAGGCTGTAAG"
				"AAATAACTTCGTTGTTGAAGAGATCTATTACTGGAGACAAATACAGCTTGCGCCCATTGACTGCAAATTCA"
				"GTAACATCGGTAACCCACTTCTCGTTTGGCCGCGTAGCCTTGAAATCTCTTTGGAGAACATTAGGGGCGGT"
				"TTGCCCTACCTCTCCTCTGTAAGAGCGGTATCGCTTGACCTTAATCGCTGCTTTAAGTGAGAGGGTTCCCA"
				"TCAGGCGCTGAACAGCTTTATGGTTAATCTGTTTCCCTTCTCGATGAAGAGACAGCGTTACCCTACGGTAT"
				"CCGTATCGGCCTCTATTCTCGTGATAAATCTCACTAATACGCTTTTTAACGTCCGCATACTTGTCAGGCTT"
				"GCTGAGAGCCTTTAGATGATAATAAAACGTACTGCGCGGTATCTCCGCAGCCCTGAGAAGCTCATCAAGAG"
				"GATAAAACTGCCTTAGCTCGTTGAGTACTTTCACTTTTTCGTGGGATGAGCTAAGGCTTTCAGCTTTTTTA"
				"GATACATAAGCCGCGTTTCAAGAAATCGAACTTGCCTTTCAAGATCCTCAATGCGTCGGTCTTTTGACAGC"
				"TCCAATGCTGATGCCGCTTTTTCTGGATCAACTGATATTGCAATGTTTCTTTTGGTGCCAATCTTGAGCGC"
				"GCGTAAACCAGCTTCTCCGCGCTCTTCATAGACCTTCAGCCACCTGGCTACAGAACCACTACCAGCAAGCA"
				"TAAAGTGAGCAGCAGCCTGATTAAGGGACATGTGCTGCTCGATCACAGCTTTCACGACCTTAATACGCAAC"
				"TCTGGATCAGCACTAACGCCTTTAGGTTTGGGAATTAAACCTTTTTCTCCATGTTTTTCATAGAGGGCAAC"
				"CCATGTCCTGACCTGGGTTCGGGGGACACCAAAACGTGCCGAGATGATCCTGTAACCATCATCAGTTGTGA"
				"AGTAGTGATTCACGACTTCAAGGCGCTTTTCAAAAGGGTATTTTGGCTTTGACATATTAGGGGCTATTCCA"
				"TTTCATCGTCCAACAAAATGGGTGCAGTACA"
			],
			var_type = 'indel',
			INFO = {'AF': [1.0], 'AD': 59.5, 'DP': 59.5},
			QUAL = None
		)
		data = {
			VCFColumns.sequence_id:  'REL606',
			VCFColumns.position:     16971,
			VCFColumns.alternate:    record.ALT[0],
			VCFColumns.reference:    "GG",
			VCFColumns.quality:      None,
			VCFColumns.depth:        59.5,
			VCFColumns.variant_type: 'indel'
		}
		table = _convert_vcf_to_table(vcf_filename)

		self.assertDictEqual(data, table[0])

	# self.assertListEqual(VCF_RECORDS, table)

	def test_filter_df_1000bp(self):
		data = [
			{VCFColumns.position: 1000, 'B': 'row1', 'C': 'col2'},
			{VCFColumns.position: 2001, 'B': 'row2', 'C': 'col2'},
			{VCFColumns.position: 3000, 'B': 'row3', 'C': 'col2'},
			{VCFColumns.position: 5000, 'B': 'row4', 'C': 'col2'},
			{VCFColumns.position: 7000, 'B': 'row5', 'C': 'col2'}
		]
		df = pandas.DataFrame(data)

		filtered_df = _filter_df(df)
		self.assertListEqual([1000, 2001, 3000, 5000, 7000], df[VCFColumns.position].tolist())
		self.assertListEqual([1000, 5000, 7000], filtered_df[VCFColumns.position].tolist())


if __name__ == "__main__":
	pass
